# Initial positions matching C++ HOME pose
# {0.0, -1.57, 1.57, -1.57, -1.57, 0.0}

initial_positions:
  elbow_joint: 1.5707
  robotiq_85_left_knuckle_joint: 0
  shoulder_lift_joint: -1.5707
  shoulder_pan_joint: 0
  wrist_1_joint: -1.5707
  wrist_2_joint: -1.5707
  wrist_3_joint: 0
