#!/usr/bin/env bash
# PAP-MoE vNext experiment contract. This wrapper makes every architecture
# change explicit while reusing the checkpoint-safe staged trainer.
set -euo pipefail

WS_DIR="/home/ubuntu/ur3_ft300_ws"

export PAP_MOE_RUN_FAMILY="${PAP_MOE_RUN_FAMILY:-pap_moe_vnext}"
export PAP_MOE_PHYSICAL_FUSION_ARCHITECTURE="${PAP_MOE_PHYSICAL_FUSION_ARCHITECTURE:-action_input_tokens_v2}"
export PAP_MOE_EXPERT_REPRESENTATION_LOSS_WEIGHT="${PAP_MOE_EXPERT_REPRESENTATION_LOSS_WEIGHT:-0.1}"
export PAP_MOE_USE_VISUAL_MEMORY="${PAP_MOE_USE_VISUAL_MEMORY:-true}"
export PAP_MOE_VISUAL_MEMORY_DISTILLATION_LOSS_WEIGHT="${PAP_MOE_VISUAL_MEMORY_DISTILLATION_LOSS_WEIGHT:-0.1}"
export PAP_MOE_VISUAL_DEGRADATION_PROBABILITY="${PAP_MOE_VISUAL_DEGRADATION_PROBABILITY:-0.5}"
export PAP_MOE_ROBUST_PHYSICS="${PAP_MOE_ROBUST_PHYSICS:-false}"
export PAP_MOE_FACTORIZED_GATE="${PAP_MOE_FACTORIZED_GATE:-true}"
export PAP_MOE_BOUNDED_CONDITIONING="${PAP_MOE_BOUNDED_CONDITIONING:-false}"
export PAP_MOE_ACTION_STEP_ROUTING="${PAP_MOE_ACTION_STEP_ROUTING:-true}"
export PAP_MOE_CONDITION_DROPOUT="${PAP_MOE_CONDITION_DROPOUT:-0.0}"
export PAP_MOE_ROUTE_JITTER_STD="${PAP_MOE_ROUTE_JITTER_STD:-0.0}"
export PAP_MOE_CONDITION_GRIPPER_WITH_EXPERTS="true"
export PAP_MOE_EXPERT_ACTION_ANCHOR_WEIGHT="0.0"

exec "${PAP_MOE_STAGE_RUNNER:-$WS_DIR/scripts/run_pap_moe_v9_stage_train.sh}" "$@"
