#!/usr/bin/env bash
# Scene-13001 evaluation of one unified Pi0.5 policy. No FSM or auxiliary head.
set -euo pipefail

WS_DIR="/home/ubuntu/ur3_ft300_ws"
CHECKPOINT="${PI05_CHECKPOINT:-$WS_DIR/outputs/train/pi05_v9_semantic_rebalanced_action_20000step_20260808_103251/checkpoints/020000/pretrained_model}"
GUI="${1:-false}"

env \
  PI05_CHECKPOINT="$CHECKPOINT" \
  PI05_STATE_GRIPPER_MODE="${PI05_STATE_GRIPPER_MODE:-continuous_0_1_closed_0.629rad}" \
  PI05_SEED="${PI05_SEED:-6}" \
  PI05_FIXED_NOISE_PER_REPLAN="${PI05_FIXED_NOISE_PER_REPLAN:-false}" \
  PI05_ENSEMBLE_SIZE="${PI05_ENSEMBLE_SIZE:-1}" \
  PI05_ACTION_CHUNK_SIZE="${PI05_ACTION_CHUNK_SIZE:-10}" \
  PI05_MAX_ARM_STEP_RAD="${PI05_MAX_ARM_STEP_RAD:-0.0}" \
  PI05_PHYSICAL_ARM_RESIDUAL_SCALE="${PI05_PHYSICAL_ARM_RESIDUAL_SCALE:-1.0}" \
  PI05_RTC_ENABLED="${PI05_RTC_ENABLED:-true}" \
  PI05_RTC_EXECUTION_HORIZON="${PI05_RTC_EXECUTION_HORIZON:-10}" \
  PI05_RTC_MAX_GUIDANCE_WEIGHT="${PI05_RTC_MAX_GUIDANCE_WEIGHT:-10.0}" \
  PI05_RTC_PREFIX_ATTENTION_SCHEDULE="${PI05_RTC_PREFIX_ATTENTION_SCHEDULE:-EXP}" \
  PI05_RECORD_VIDEO="${PI05_RECORD_VIDEO:-true}" \
  PI05_TRACE_FIRST_CHUNKS="${PI05_TRACE_FIRST_CHUNKS:-80}" \
  PI05_TRACE_MULTIMODAL="${PI05_TRACE_MULTIMODAL:-true}" \
  PI05_DYNAMIC_TASK_PROMPT=false \
  PI05_HOLD_GRIPPER_PER_REPLAN=false \
  PI05_HOLD_ARM_ON_CLOSE=false \
  PI05_DEMO_RECOVERY_EPISODE= \
  PI05_ROLLOUT_RECOVERY_SESSION_DIR= \
  PI05_LAUNCH_MOVEIT_FOR_RECOVERY=false \
  PI05_ACTION_OUT_ADAPTER= \
  PI05_LORA_ADAPTER= \
  PI05_STAGE_LORA_ADAPTER= \
  PI05_STAGE_LORA_REFERENCE= \
  PI05_FINAL_STAGE_LORA_ADAPTER= \
  PI05_FINAL_STAGE_LORA_REFERENCE= \
  PI05_GRASP_STAGE_LORA_ADAPTER= \
  PI05_GRASP_STAGE_LORA_REFERENCE= \
  PI05_POST_GRASP_LORA_ADAPTER= \
  PI05_POST_GRASP_LORA_REFERENCE= \
  PI05_INSERTION_LORA_ADAPTER= \
  PI05_INSERTION_LORA_REFERENCE= \
  PI05_CONTACT_LORA_ADAPTER= \
  PI05_CONTACT_LORA_REFERENCE= \
  PI05_INSERTION_FEEDBACK_ADAPTER= \
  PI05_GRIPPER_CLOSE_REFERENCE= \
  PI05_GRIPPER_OPEN_REFERENCE= \
  bash "$WS_DIR/scripts/run_pi05_v9_absolute_gazebo_eval.sh" "$GUI" 13001
